// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutQ9ACO6La8ifZ2DBFaQ17DQEMiJag88',
    appId: '1:672954509821:web:31c07470495628f7fe1194',
    messagingSenderId: '672954509821',
    projectId: 'ithapp-d147e',
    authDomain: 'ithapp-d147e.firebaseapp.com',
    storageBucket: 'ithapp-d147e.firebasestorage.app',
    measurementId: 'G-TG7H1M13C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoZbthnv6VgRDiiotEMF8giXnwvXvWMc',
    appId: '1:672954509821:android:f8f71856fc22cdd5fe1194',
    messagingSenderId: '672954509821',
    projectId: 'ithapp-d147e',
    storageBucket: 'ithapp-d147e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtbiOuu7iAQf3loI4BQQxMfKqFFVJO38',
    appId: '1:672954509821:ios:1a23468151abc2ccfe1194',
    messagingSenderId: '672954509821',
    projectId: 'ithapp-d147e',
    storageBucket: 'ithapp-d147e.firebasestorage.app',
    iosBundleId: 'com.mycompany.ithapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutQ9ACO6La8ifZ2DBFaQ17DQEMiJag88',
    appId: '1:672954509821:web:99c19d62a6b45a7efe1194',
    messagingSenderId: '672954509821',
    projectId: 'ithapp-d147e',
    authDomain: 'ithapp-d147e.firebaseapp.com',
    storageBucket: 'ithapp-d147e.firebasestorage.app',
    measurementId: 'G-S5DQLPY31V',
  );
}
